spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: banco-mysql

  sql:
    init:
      mode: always

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true